"""Add categories and tax_categories tables

Revision ID: a526473d55e3
Revises: 702ba75b54b0
Create Date: 2026-01-21 09:53:28.957201

"""
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

from app.shared.seed_data import SEED_CATEGORIES, SEED_TAX_CATEGORIES


# revision identifiers, used by Alembic.
revision: str = 'a526473d55e3'
down_revision: Union[str, None] = '702ba75b54b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('name_de', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_categories',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('name_de', sa.String(length=100), nullable=False),
    sa.Column('anlage', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('deductible_percent', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_categories_name'), 'tax_categories', ['name'], unique=True)
    # ### end Alembic commands ###

    # Insert seed data
    connection = op.get_bind()

    # Insert tax categories
    for tax_cat in SEED_TAX_CATEGORIES:
        connection.execute(
            text("""
                INSERT INTO tax_categories (id, name, name_de, anlage, description, deductible_percent, created_at, updated_at)
                VALUES (:id, :name, :name_de, :anlage, :description, :deductible_percent, now(), now())
            """),
            {
                "id": str(uuid4()),
                "name": tax_cat["name"],
                "name_de": tax_cat["name_de"],
                "anlage": tax_cat.get("anlage"),
                "description": tax_cat.get("description"),
                "deductible_percent": tax_cat["deductible_percent"],
            }
        )

    # Insert categories (parents first, then children)
    for cat in SEED_CATEGORIES:
        parent_id = str(uuid4())
        connection.execute(
            text("""
                INSERT INTO categories (id, name, name_de, parent_id, is_income, icon, color, sort_order, created_at, updated_at)
                VALUES (:id, :name, :name_de, :parent_id, :is_income, :icon, :color, :sort_order, now(), now())
            """),
            {
                "id": parent_id,
                "name": cat["name"],
                "name_de": cat["name_de"],
                "parent_id": None,
                "is_income": cat["is_income"],
                "icon": cat["icon"],
                "color": cat["color"],
                "sort_order": cat["sort_order"],
            }
        )

        # Insert children if present
        for child in cat.get("children", []):
            connection.execute(
                text("""
                    INSERT INTO categories (id, name, name_de, parent_id, is_income, icon, color, sort_order, created_at, updated_at)
                    VALUES (:id, :name, :name_de, :parent_id, :is_income, :icon, :color, :sort_order, now(), now())
                """),
                {
                    "id": str(uuid4()),
                    "name": child["name"],
                    "name_de": child["name_de"],
                    "parent_id": parent_id,
                    "is_income": cat["is_income"],
                    "icon": child["icon"],
                    "color": cat["color"],
                    "sort_order": child["sort_order"],
                }
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_categories_name'), table_name='tax_categories')
    op.drop_table('tax_categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
