"""Add transactions table

Revision ID: e233d0c71ed4
Revises: a526473d55e3
Create Date: 2026-01-21 10:00:54.439571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e233d0c71ed4'
down_revision: Union[str, None] = 'a526473d55e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.Column('account_iban_last4', sa.String(length=4), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('counterparty', sa.String(length=255), nullable=True),
    sa.Column('counterparty_iban', sa.String(length=34), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('e_ref', sa.String(length=100), nullable=True),
    sa.Column('mandate_ref', sa.String(length=100), nullable=True),
    sa.Column('creditor_id', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('tax_category_id', sa.UUID(), nullable=True),
    sa.Column('fg_main_category', sa.String(length=100), nullable=True),
    sa.Column('fg_subcategory', sa.String(length=100), nullable=True),
    sa.Column('fg_contract_name', sa.String(length=100), nullable=True),
    sa.Column('fg_contract_frequency', sa.String(length=20), nullable=True),
    sa.Column('fg_contract_id', sa.String(length=50), nullable=True),
    sa.Column('fg_is_transfer', sa.Boolean(), nullable=False),
    sa.Column('fg_excluded_from_budget', sa.Boolean(), nullable=False),
    sa.Column('fg_transaction_type', sa.String(length=50), nullable=True),
    sa.Column('fg_analysis_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fg_week', sa.String(length=10), nullable=True),
    sa.Column('fg_month', sa.String(length=10), nullable=True),
    sa.Column('fg_quarter', sa.String(length=10), nullable=True),
    sa.Column('fg_year', sa.String(length=10), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('import_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['tax_category_id'], ['tax_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_import_hash'), 'transactions', ['import_hash'], unique=True)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_import_hash'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
