"""Seed data for categories and tax categories."""

# Default categories with German translations
SEED_CATEGORIES = [
    {
        "name": "Income",
        "name_de": "Einnahmen",
        "is_income": True,
        "icon": "TrendingUp",
        "color": "#16A34A",
        "sort_order": 0,
        "children": [
            {"name": "Salary", "name_de": "Gehalt", "icon": "Briefcase", "sort_order": 0},
            {"name": "Freelance", "name_de": "Freiberuflich", "icon": "Laptop", "sort_order": 1},
            {"name": "Investment", "name_de": "Kapitalerträge", "icon": "PiggyBank", "sort_order": 2},
            {"name": "Other Income", "name_de": "Sonstige Einnahmen", "icon": "Plus", "sort_order": 3},
        ],
    },
    {
        "name": "Food & Groceries",
        "name_de": "Lebensmittel",
        "is_income": False,
        "icon": "ShoppingCart",
        "color": "#DC2626",
        "sort_order": 1,
        "children": [
            {"name": "Supermarket", "name_de": "Supermarkt", "icon": "Store", "sort_order": 0},
            {"name": "Restaurant", "name_de": "Restaurant", "icon": "Utensils", "sort_order": 1},
            {"name": "Delivery", "name_de": "Lieferservice", "icon": "Bike", "sort_order": 2},
            {"name": "Cafe", "name_de": "Café", "icon": "Coffee", "sort_order": 3},
        ],
    },
    {
        "name": "Housing",
        "name_de": "Wohnen",
        "is_income": False,
        "icon": "Home",
        "color": "#2563EB",
        "sort_order": 2,
        "children": [
            {"name": "Rent", "name_de": "Miete", "icon": "Key", "sort_order": 0},
            {"name": "Utilities", "name_de": "Nebenkosten", "icon": "Zap", "sort_order": 1},
            {"name": "Internet", "name_de": "Internet", "icon": "Wifi", "sort_order": 2},
            {"name": "Furniture", "name_de": "Möbel", "icon": "Sofa", "sort_order": 3},
        ],
    },
    {
        "name": "Transportation",
        "name_de": "Mobilität",
        "is_income": False,
        "icon": "Car",
        "color": "#7C3AED",
        "sort_order": 3,
        "children": [
            {"name": "Public Transit", "name_de": "ÖPNV", "icon": "Train", "sort_order": 0},
            {"name": "Fuel", "name_de": "Tanken", "icon": "Fuel", "sort_order": 1},
            {"name": "Car Maintenance", "name_de": "Auto Wartung", "icon": "Wrench", "sort_order": 2},
            {"name": "Taxi", "name_de": "Taxi", "icon": "Car", "sort_order": 3},
        ],
    },
    {
        "name": "Shopping",
        "name_de": "Einkaufen",
        "is_income": False,
        "icon": "ShoppingBag",
        "color": "#EA580C",
        "sort_order": 4,
        "children": [
            {"name": "Clothing", "name_de": "Kleidung", "icon": "Shirt", "sort_order": 0},
            {"name": "Electronics", "name_de": "Elektronik", "icon": "Smartphone", "sort_order": 1},
            {"name": "Household", "name_de": "Haushalt", "icon": "Package", "sort_order": 2},
            {"name": "Books", "name_de": "Bücher", "icon": "Book", "sort_order": 3},
        ],
    },
    {
        "name": "Health",
        "name_de": "Gesundheit",
        "is_income": False,
        "icon": "Heart",
        "color": "#DB2777",
        "sort_order": 5,
        "children": [
            {"name": "Pharmacy", "name_de": "Apotheke", "icon": "Pill", "sort_order": 0},
            {"name": "Doctor", "name_de": "Arzt", "icon": "Stethoscope", "sort_order": 1},
            {"name": "Insurance", "name_de": "Versicherung", "icon": "Shield", "sort_order": 2},
            {"name": "Fitness", "name_de": "Fitness", "icon": "Dumbbell", "sort_order": 3},
        ],
    },
    {
        "name": "Entertainment",
        "name_de": "Freizeit",
        "is_income": False,
        "icon": "Film",
        "color": "#0891B2",
        "sort_order": 6,
        "children": [
            {"name": "Subscriptions", "name_de": "Abonnements", "icon": "Tv", "sort_order": 0},
            {"name": "Sports", "name_de": "Sport", "icon": "Activity", "sort_order": 1},
            {"name": "Culture", "name_de": "Kultur", "icon": "Music", "sort_order": 2},
            {"name": "Hobbies", "name_de": "Hobbys", "icon": "Palette", "sort_order": 3},
        ],
    },
    {
        "name": "Education",
        "name_de": "Bildung",
        "is_income": False,
        "icon": "GraduationCap",
        "color": "#65A30D",
        "sort_order": 7,
        "children": [
            {"name": "Courses", "name_de": "Kurse", "icon": "BookOpen", "sort_order": 0},
            {"name": "Books & Materials", "name_de": "Bücher & Material", "icon": "Notebook", "sort_order": 1},
        ],
    },
    {
        "name": "Transfers",
        "name_de": "Umbuchungen",
        "is_income": False,
        "icon": "ArrowLeftRight",
        "color": "#64748B",
        "sort_order": 98,
    },
    {
        "name": "Other",
        "name_de": "Sonstiges",
        "is_income": False,
        "icon": "MoreHorizontal",
        "color": "#71717A",
        "sort_order": 99,
    },
]

# German tax categories (Steuerkategorien)
SEED_TAX_CATEGORIES = [
    # Werbungskosten (Anlage N)
    {
        "name": "work_equipment",
        "name_de": "Arbeitsmittel",
        "anlage": "N",
        "description": "Werkzeuge, Computer, Fachbücher für berufliche Zwecke",
        "deductible_percent": 100,
    },
    {
        "name": "commuting",
        "name_de": "Fahrtkosten (Pendlerpauschale)",
        "anlage": "N",
        "description": "Entfernungspauschale für Fahrten zwischen Wohnung und Arbeitsstätte",
        "deductible_percent": 100,
    },
    {
        "name": "professional_development",
        "name_de": "Fortbildung",
        "anlage": "N",
        "description": "Berufliche Weiterbildung und Qualifizierung",
        "deductible_percent": 100,
    },
    {
        "name": "home_office",
        "name_de": "Homeoffice-Pauschale",
        "anlage": "N",
        "description": "Pauschale für häusliches Arbeitszimmer (6€/Tag, max 1.260€/Jahr)",
        "deductible_percent": 100,
    },
    {
        "name": "double_household",
        "name_de": "Doppelte Haushaltsführung",
        "anlage": "N",
        "description": "Kosten für Zweitwohnung am Arbeitsort",
        "deductible_percent": 100,
    },
    # Sonderausgaben
    {
        "name": "insurance",
        "name_de": "Versicherungen (Vorsorgeaufwand)",
        "anlage": "Vorsorgeaufwand",
        "description": "Kranken-, Pflege-, Rentenversicherung, Haftpflicht",
        "deductible_percent": 100,
    },
    {
        "name": "donations",
        "name_de": "Spenden",
        "anlage": "Sonderausgaben",
        "description": "Gemeinnützige Spenden und Mitgliedsbeiträge",
        "deductible_percent": 100,
    },
    {
        "name": "church_tax",
        "name_de": "Kirchensteuer",
        "anlage": "Sonderausgaben",
        "description": "Kirchensteuer",
        "deductible_percent": 100,
    },
    {
        "name": "retirement_savings",
        "name_de": "Altersvorsorge (Riester/Rürup)",
        "anlage": "Sonderausgaben",
        "description": "Beiträge zur privaten Altersvorsorge",
        "deductible_percent": 100,
    },
    # Haushaltsnahe Dienstleistungen
    {
        "name": "craftsman_services",
        "name_de": "Handwerkerleistungen",
        "anlage": "Haushaltsnahe Dienstleistungen",
        "description": "Handwerkerrechnungen für Renovierung, Reparatur (20% bis 1.200€)",
        "deductible_percent": 20,
    },
    {
        "name": "household_services",
        "name_de": "Haushaltsnahe Dienstleistungen",
        "anlage": "Haushaltsnahe Dienstleistungen",
        "description": "Reinigung, Gartenpflege, Kinderbetreuung (20% bis 4.000€)",
        "deductible_percent": 20,
    },
    # Außergewöhnliche Belastungen
    {
        "name": "medical_expenses",
        "name_de": "Krankheitskosten",
        "anlage": "Außergewöhnliche Belastungen",
        "description": "Arztkosten, Medikamente, Hilfsmittel (nach zumutbarer Belastung)",
        "deductible_percent": 100,
    },
    {
        "name": "care_costs",
        "name_de": "Pflegekosten",
        "anlage": "Außergewöhnliche Belastungen",
        "description": "Kosten für Pflege von Angehörigen",
        "deductible_percent": 100,
    },
    {
        "name": "disability",
        "name_de": "Behindertenpauschbetrag",
        "anlage": "Außergewöhnliche Belastungen",
        "description": "Pauschbetrag bei Behinderung",
        "deductible_percent": 100,
    },
    # Kindbezogen
    {
        "name": "childcare",
        "name_de": "Kinderbetreuungskosten",
        "anlage": "Kind",
        "description": "Betreuung für Kinder unter 14 Jahren (2/3 bis 4.000€/Kind)",
        "deductible_percent": 67,
    },
]
